# My b. don't change this name thing
name: chicano_park
description: Chicano Park Explorer, learn about Chicano Park's murals
version: 0.9+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.5.7+3
  firebase_core: ^0.4.3+2
  cloud_firestore: ^0.13.0+1
  firebase_storage: ^3.1.1
  transparent_image: ^1.0.0
  path_provider: ^1.5.1
  path: ^1.6.4
  flutter_counter: ^1.0.3
  permission_handler: '^4.2.0+hotfix.2'
  flutter_tts: ^0.8.6
  share: ^0.6.3+5
  flutter_webview_plugin: ^0.3.10+1
  firebase_analytics: ^5.0.2
  sliding_up_panel: ^1.0.0
  url_launcher: ^5.4.1
  flare_splash_screen: ^3.0.1
  flare_flutter: ^2.0.1
  cupertino_icons: ^0.1.2
  audioplayers: ^0.14.0
  flutter_animation_progress_bar: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
  
flutter_icons:
  android: "launcher_icon_new"
  ios: true
  image_path: "assets/icons/cp_icon.png"
  adaptive_icon_foreground: "assets/icons/icon.png"
  adaptive_icon_background: "#F6F3D6"


# The following section is specific to Flutter. DO not change.
flutter:
  uses-material-design: true
  assets:
    - assets/ml/dict.txt
    - assets/ml/model.tflite
    - assets/ml/manifest.json
    - assets/Chicano.flr
    - assets/Camera.flr