name: chicano_park
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  # See https://pub.dev/packages/camera for more info
  camera: ^0.5.6+3
  firebase_core: ^0.4.0+9
  # firebase_analytics: ^5.0.2
  cloud_firestore: ^0.12.9+5
  firebase_storage: ^3.0.8
  transparent_image: ^1.0.0
  share: ^0.6.3+1
  firebase_livestream_ml_vision: ^1.0.1
  tflite: ^1.0.4

dev_dependencies:
  flutter_launcher_icons: ^0.7.3
  
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/ml/model.tflite
    - assets/ml/dict.txt
    - assets/ml/manifest.json
  fonts:
    - family: Baskerville
      fonts:
        - asset: fonts/baskerville.ttf
          style: normal
flutter_icons:
    android: "launcher_icon" 
    ios: true
    image_path: "assets/icons/icon.png"
    adaptive_icon_background: "#D5D863"
    adaptive_icon_foreground: "assets/icons/icon.png"
