name: chicano_park
description: u know...
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.7.1"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  # See https://pub.dev/packages/camera for more info
  camera: ^0.5.7+2
  firebase_core: ^0.4.3
  # firebase_analytics: ^5.0.2
  cloud_firestore: ^0.13.0+1
  firebase_storage: ^3.0.11
  transparent_image: ^1.0.0
  share: ^0.6.3+5
  firebase_livestream_ml_vision: ^1.0.1
  flutter_speed_dial: ^1.2.5

dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/ml/model.tflite
    - assets/ml/dict.txt
    - assets/ml/manifest.json
  fonts:
    - family: Baskerville
      fonts:
        - asset: fonts/baskerville.ttf
          style: normal
flutter_icons:
    android: "launcher_icon" 
    ios: true
    image_path: "assets/icons/icon.png"
    adaptive_icon_background: "#D5D863"
    adaptive_icon_foreground: "assets/icons/icon.png"
